# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Build_Firefox
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        echo ${{ github.workspace }}
        ls -lhat .
        npm run build-firefox        
        mv ./dist ./datawallet-firefox
        cd ./datawallet-firefox; zip -r "$GITHUB_WORKSPACE/datawallet-firefox.zip" ./*; cd ..
        
    - name: Build_Chrome
      run: |
        ls -lhat .
        npm run build-chrome       
        mv ./dist ./datawallet-chrome
        cd ./datawallet-chrome; zip -r "$GITHUB_WORKSPACE/datawallet-chrome.zip" ./*; cd ..

    - name: Release_Firefox
      uses: fnkr/github-action-ghr@v1
      if: ${{ github.ref_type == 'tag' }}
      env:        
        GHR_PATH: /home/runner/work/datawallet/datawallet/datawallet-firefox.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release_Chrome
      uses: fnkr/github-action-ghr@v1
      if: ${{ github.ref_type == 'tag' }}
      env:        
        GHR_PATH: /home/runner/work/datawallet/datawallet/datawallet-chrome.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify_Releases_Reproducibility
      run: |
        # Create and start from new directory
        mkdir verification
        cd verification
        
        # Download and extract datawallet-firefox.zip
        wget "https://github.com/OpenOdin/datawallet/releases/download/${{  github.ref_name  }}/datawallet-firefox.zip"
        unzip -d datawallet-firefox datawallet-firefox.zip

        # Download and extract datawallet-chrome.zip
        wget "https://github.com/OpenOdin/datawallet/releases/download/${{  github.ref_name  }}/datawallet-chrome.zip"
        unzip -d datawallet-chrome datawallet-chrome.zip

        # Download and extract source code
        wget "https://github.com/OpenOdin/datawallet/archive/refs/tags/${{  github.ref_name  }}.zip"
        unzip -d src "${{  github.ref_name }}.zip"

        # Enter source directory and prepare
        cd src/datawallet-"${{github.ref_name}}/"
        npm i

        # Build Firefox release from source and compare to published release
        npm run build-firefox
        diff -rq ./dist ../../datawallet-firefox

        rm -rf ./dist

        # Build Chrome release from source and compare to published release
        npm run build-chrome
        diff -rq ./dist ../../datawallet-chrome
